apiVersion: v2
name: airflow
description: A Helm chart for Apache Airflow using Bitnami
type: application
version: 1.0.0
appVersion: "3.0.0"
dependencies:
  - name: airflow
    version: ">=1.0.0"
    repository: https://charts.bitnami.com/bitnami

